apiVersion: v1
kind: Service
metadata:
  name: mdb-standalone-svc-ext
spec:
  type: NodePort
  selector:
    app: mdb-standalone-svc
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30017